include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error Rules
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - empty_catches
    - hash_and_equals
    - implementation_imports
    - no_duplicate_case_values
    - non_constant_identifier_names
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_null_aware_operators
    - prefer_relative_imports
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - unrelated_type_equality_checks

    # Style Rules
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_as
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_redundant_argument_values
    - avoid_return_types_on_setters
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - no_logic_in_create_state
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_declarations
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - sort_child_properties_last
    - unnecessary_const
    - unnecessary_overrides
    - use_key_in_widget_constructors
